# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import naive_chatbot.predictor_pb2 as predictor__pb2


class ChatPredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictOne = channel.unary_unary(
            '/ChatPredictor/PredictOne',
            request_serializer=predictor__pb2.PredictRequest.SerializeToString,
            response_deserializer=predictor__pb2.PredictReply.FromString,
        )


class ChatPredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictOne(self, request, context):
        """get predictions for one chat msg
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PredictOne': grpc.unary_unary_rpc_method_handler(
            servicer.PredictOne,
            request_deserializer=predictor__pb2.PredictRequest.FromString,
            response_serializer=predictor__pb2.PredictReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ChatPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ChatPredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictOne(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ChatPredictor/PredictOne',
                                             predictor__pb2.PredictRequest.SerializeToString,
                                             predictor__pb2.PredictReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
